be more permissive by default
cmeissner/puppet-git-hooks pull request #9
Opened 2021-03-15 19:30 UTC by anarcat

We stop failing on docs test by default, and avoid failing on linting warnings.

This is a matter of policy I guess, but since there's no way to modify the config short of committing to the repository, I figured I would share my own configurations. Ideally, those kind of site-local policies could be established without having to edit the worktree...

2021-03-16 18:31 UTC, cmeissner requested changes
Please change `CHECK_PUPPET_DOCS` back to `enable`. This should be solved at local environment.

2021-03-16 18:31 UTC, cmeissner commented on commit_hooks/config.cfg
> +CHECK_PUPPET_DOCS="permissive" # enabled, permissive or disabled (permissive runs but return code is ignored)
having docs is not negotiable for us. So it should stay on `enable` instead of `permissive`.

2021-03-16 18:31 UTC, cmeissner commented on commit_hooks/config.cfg
> +export PUPPET_LINT_FAIL_ON_WARNINGS="false" # Set the puppet-lint option --fail-on-warnings
This is okay.

2021-03-16 18:41 UTC, anarcat commented
> Please change `CHECK_PUPPET_DOCS` back to `enable`. This should be solved at local environment.

how do you actually do this in this repo? it seems i necessarily have to fork the repo, or can we have configs not checked in?

2021-03-16 18:48 UTC, cmeissner commented
> how do you actually do this in this repo? it seems i necessarily have to fork the repo, or can we have configs not checked in?

We solved this by a script in our control repo. Here you can modify all params by search and replace.

2021-03-16 18:54 UTC, anarcat commented
> We solved this by a script in our control repo. Here you can modify all params by search and replace.

isn't *this* the script that runs from your control repo? I think I don't understand. :)

2021-03-16 19:14 UTC, cmeissner commented
> isn't *this* the script that runs from your control repo? I think I don't understand. :)

This are the local git hooks. To install it, we provide a script, which clone the repo and install the hooks. At this time modifications are possible.

2021-03-16 19:27 UTC, anarcat commented
> This are the local git hooks. To install it, we provide a script, which clone the repo and install the hooks. At this time modifications are possible.

sorry for the multiple questions, but you basically patch the git worktree on deployment?

2021-03-17 11:34 UTC, cmeissner commented
The repository is intended to help developers of a control-repo to push only clean code. The nature of the hooks of this repo is that they are client-side hooks and have to be installed in `.git/hooks` directory. 
The project in which we introduce these hooks had to decide to clone the repo directly to the hooks directory or to provide a way to install the hooks without the complete `.git` overhead. This is why we provide a skript in control-repo `install-hooks.sh`. This does the following:


1. clone these repo to a temporary directory
2. copy the scripts in place (`.git/hooks`)
3. modify `config.cfg` as the policy requires


What this repo is not indended for it to use it at deployment time. Hopefully this make some things clear.

2021-03-17 11:39 UTC, cmeissner approved these changes
LGTM

2021-03-17 11:40 UTC, merged

2021-03-17 12:47 UTC, anarcat commented
> What this repo is not indended for it to use it at deployment time. Hopefully this make some things clear.

interesting. this is definitely out of scope for this PR, but since you don't have issues enabled (and seem more active than the upstream), i'll dare ask more. :)

i'm surprised: there are definitely server-side hooks in here: `pre-receive`, `update` all run on deployment time, don't they?

anyways, i guess i should figure out a way to load an external config file so we don't have to modify the worktree, would you be open to such a PR?

2021-03-17 17:20 UTC, cmeissner commented
I transferred the repo to our open source org [codeaffen](https://github.com/codeaffen) here. I also activate discussions, where we can discuss further.